[tool.black]
line-length = 100

[tool.ruff]
line-length = 100
src = ["."]
exclude = [
  ".git",
  ".mypy_cache",
  ".ruff_cache",
  ".venv",
  "snapshots",
]

[tool.ruff.lint]
select = [
  # pycodestyle
  "E",
  # pyflakes
  "F",
  # pep8-naming
  "N",
  # flake8-unused-arguments
  "ARG",
  # pyupgrade
  "UP",
  # flake-bugbear
  "B",
  # flake8-builtins
  "A",
  # isort
  "I",
  # flake8-comprehensions
  "C4",
  # flake8-import-conventions
  "ICN",
  # flake8-pytest-style
  "PT",
  # flake8-simplify
  "SIM",
  # pandas-vet
  "PD",
  # flake8-use-pathlib - in ruff/main but not yet in the nixified version
  # "PTH",
]
ignore = [
  # Allow shadowing builtins on attributes.
  "A003",
  # Do not enforce max line length via linter. We have an autoformatter, and sometimes we
  # intentionally turn formatting off.
  "E501",
  # Fixtures that do not return anything do not need leading underscore.
  "PT004",
]
unfixable = [
  # Remove unused variables.
  "F841",
]

[tool.mypy]
strict = true
strict_optional = true
explicit_package_bases = true

[[tool.mypy.overrides]]
module = "fuse"
ignore_missing_imports = true
[[tool.mypy.overrides]]
module = "pytest_cov.embed"
ignore_missing_imports = true
[[tool.mypy.overrides]]
module = "llfuse"
ignore_missing_imports = true
[[tool.mypy.overrides]]
module = "send2trash"
ignore_missing_imports = true
[[tool.mypy.overrides]]
module = "appdirs.*"
ignore_missing_imports = true
[[tool.mypy.overrides]]
module = "watchdog.*"
ignore_missing_imports = true
[[tool.mypy.overrides]]
module = "setuptools"
ignore_missing_imports = true
[[tool.mypy.overrides]]
module = "snapshottest"
ignore_missing_imports = true
[[tool.mypy.overrides]]
module = "cffi"
ignore_missing_imports = true

[tool.pytest.ini_options]
addopts = [
  "--cov=.",
  "--cov-branch",
  "--import-mode=importlib",
  "--ignore=result",
]
pythonpath = "."
python_files = ["*_test.py", "__test__.py"]
