//! Genre hierarchy data structures.
//!
//! Provides two lazily-initialized lookup tables derived from the RateYourMusic
//! genre taxonomy (generated by `scripts/rym-genres/generate.py`):
//!
//! - [`GENRE_HIERARCHY`]: child genre → transitive parent genres.
//! - [`TRANSITIVE_CHILD_GENRES`]: parent genre → transitive child genres (inverse).

use std::collections::HashMap;
use std::sync::LazyLock;

/// Child genre → list of transitive parent genres.
///
/// Loaded at first access from the embedded JSON file produced by the generator
/// script.  The JSON is included at compile time via `include_str!`.
pub static GENRE_HIERARCHY: LazyLock<HashMap<String, Vec<String>>> = LazyLock::new(|| {
    let json_str = include_str!("genre_hierarchy.json");
    serde_json::from_str(json_str).expect("genre_hierarchy.json is invalid")
});

/// Parent genre → list of transitive child genres.
///
/// Computed at first access by inverting [`GENRE_HIERARCHY`].
pub static TRANSITIVE_CHILD_GENRES: LazyLock<HashMap<String, Vec<String>>> = LazyLock::new(|| {
    let mut children: HashMap<String, Vec<String>> = HashMap::new();
    for (child, parents) in GENRE_HIERARCHY.iter() {
        for parent in parents {
            children
                .entry(parent.clone())
                .or_default()
                .push(child.clone());
        }
    }
    // Sort each child list for deterministic ordering.
    for list in children.values_mut() {
        list.sort();
    }
    children
});

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn genre_hierarchy_is_not_empty() {
        assert!(
            !GENRE_HIERARCHY.is_empty(),
            "GENRE_HIERARCHY should contain entries"
        );
    }

    #[test]
    fn known_entry_acid_house() {
        let parents = GENRE_HIERARCHY
            .get("Acid House")
            .expect("Acid House should exist in GENRE_HIERARCHY");
        assert!(
            parents.contains(&"House".to_string()),
            "Acid House parents should contain House"
        );
        assert!(
            parents.contains(&"Electronic Dance Music".to_string()),
            "Acid House parents should contain Electronic Dance Music"
        );
    }

    #[test]
    fn inverse_correctness() {
        // For every (child, parents) in GENRE_HIERARCHY, each parent's entry in
        // TRANSITIVE_CHILD_GENRES must contain that child.
        for (child, parents) in GENRE_HIERARCHY.iter() {
            for parent in parents {
                let children = TRANSITIVE_CHILD_GENRES.get(parent).unwrap_or_else(|| {
                    panic!("parent {parent:?} missing from TRANSITIVE_CHILD_GENRES")
                });
                assert!(
                    children.contains(child),
                    "TRANSITIVE_CHILD_GENRES[{parent:?}] should contain {child:?}"
                );
            }
        }
    }

    #[test]
    fn inverse_completeness() {
        // Every genre that appears as a parent in GENRE_HIERARCHY must have an
        // entry in TRANSITIVE_CHILD_GENRES.
        for parents in GENRE_HIERARCHY.values() {
            for parent in parents {
                assert!(
                    TRANSITIVE_CHILD_GENRES.contains_key(parent),
                    "Parent genre {parent:?} should have an entry in TRANSITIVE_CHILD_GENRES"
                );
            }
        }
    }

    #[test]
    fn no_self_references() {
        for (genre, parents) in GENRE_HIERARCHY.iter() {
            assert!(
                !parents.contains(genre),
                "GENRE_HIERARCHY: {genre:?} should not map to itself"
            );
        }
        for (genre, children) in TRANSITIVE_CHILD_GENRES.iter() {
            assert!(
                !children.contains(genre),
                "TRANSITIVE_CHILD_GENRES: {genre:?} should not map to itself"
            );
        }
    }
}
