name: build
on: push
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v20
      - uses: cachix/cachix-action@v12
        with:
          name: rose
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - name: Build Nix
        run: nix build -j8 .#devShells.x86_64-linux.default
      - name: Typecheck
        if: success() || failure() # Means that we run all steps even if one fails.
        run: nix develop --command make typecheck
      - name: Test
        if: success() || failure()
        run: nix develop --command make test
      - name: Lint
        if: success() || failure()
        run: nix develop --command make lintcheck
      - name: Build
        if: success() || failure()
        run: nix build .#all
